### PR TITLE
Add information about additional translation sources to README

### PR DESCRIPTION
**Pull request by mentaljam**

### CODE REVIEW

**Comment by jpetrell** [comment]
LGTM

Merged commits require one change log entry which is created with postfix "[..]" e.g.  "[libsailfishapp]" or "[localization]" in the commit message, and reference to https://bugs.merproject.org/ bug like "Fixes MER#123" or "Contributes to MER#123". E.g. "[localization] Add information about additional translation sources to README. Contributes to MER#12345"

**Comment by mentaljam** [comment]
Thank you for the reply. I see that commits here often refer to `JB#...`. Where are these ids from?

**Comment by M4rtinK** [comment]
@mentaljam AFAIK (I'm a community developer, not a Jolla employee) the JB# identifier reffers to the the private **J**olla **B**ugzilla instance. IIRC it's private because it sometime contains internal Jolla & Jolla customer/partner information. So I'm afraid tha the JB# identifier is of little use to the community as all of the bugs referenced reside in the private bugzilla only accessible to Jolla.

(On the topic of public/private Bugzilla, the bugzilla.redhat.com instance is shared between Fedora and Red Hat Enterprise Linux and **does** contain both public and private information, protected via private/public bugs and private/public comments, with access governed by respective user groups.)

**Comment by mentaljam** [comment]
So there is no possibility for community contributors to format commits as they're required. Or am I missing something?

**Comment by M4rtinK** [comment]
@mentaljam I guess you still can reffer to bugs in the Mer bugzilla (which is public) by MER#<number>. Of course an authoritative answer from one of the actual maintainers should be be preffered over my guesses. :)

BTW, looking at [the how-to-contribute docs I found](https://wiki.merproject.org/wiki/Contribution) I don't see any guidelines for commint message formatting. Certainly something to add there IMHO. :)

**Comment by martyone** [comment]
@mentaljam read again jpetrell's comment https://github.com/sailfishos/libsailfishapp/pull/37#issuecomment-357545849 :)

**Comment by mentaljam** [comment]
@martyone, I've read jpetrell's comment carefully and also I've already read the [Collaborative Development](https://sailfishos.org/wiki/Collaborative_Development) wiki and I've already seen the [Mer Bugtracker](https://bugs.merproject.org). But I haven't found an appropriate category or bugs that refer to libsailfishapp and commits here often refer to `JB#`. So all these facts make me feel confused and I just decided to clarify for myself how can I contribute.

And as I understand for now I should:
1. Mail to david@dgreaves.com to get a bugs.merproject.org account
2. File a new bug
3. Format my commit with a reference to my newly filed bug

Did I miss something?

P.S.: @M4rtinK, guidelines for commit message formatting could be find [here](https://sailfishos.org/wiki/Collaborative_Development).

**Comment by martyone** [comment]
@mentaljam correct. I would file it against "mer-core" product, category ".Other" - it can be improved later. And/or ask David in your email.

**Comment by mentaljam** [comment]
The commit message was fixed

**Comment by jpetrell** [comment]
Discussed with @pvuorela that we probably shouldn't require strict process with these small fixes. He is right. Sorry for the hassle though it is good to learn the process. :)

**Comment by mentaljam** [comment]
Oh, don't worry! It was useful for me and if sometime I decide to contribute again I would make it right))

**Comment by pvuorela** [comment]
LGTM. Though a bit pondering if translations should by default use just '.' dir. But let's just have this now.

**Pull request merged**
